### ISSUE TITLE
Not working with UE58MU6199

### ISSUE THREAD

**Issue by DavidLP** [tdudek/samsung-remote-models-2014-and-newer#10]
I cannot connect to the television (network ping works) and get the following:
```bash
node requestPin.js -ip 192.168.1.215
```
Reply:
```bash
Initializing device configuration
Fetching device info
(node:3486) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://192.168.1.215:8001/ms/1.0/ reason: Unexpected token < in JSON at position 0
    at /home/ha/git/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/node_modules/node-fetch/lib/index.js:252:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:3486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by DavidLP** [comment]
This model uses Tizen and works with https://github.com/Ape/samsungctl
