### ISSUE TITLE
Not Working on UN55MU6290

### ISSUE THREAD

**Issue by mitchshaw** [tdudek/samsung-remote-models-2014-and-newer#19]
Hello! I'm currently attempting to connect to 2 UN55MU6290s and when trying either of them through the Web Interface to pair with the PIN, I get the following error:

```
Initializing device configuration
Fetching device info
Debug: internal, implementation, error
    TypeError: Cannot read property 'requestPin' of null
    at SamsungTv.requestPin (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\node_modules\samsung-remote\lib\SamsungTv.js:47:25)
    at handler (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\server.js:46:22)
    at module.exports.internals.Manager.execute (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\node_modules\hapi\lib\toolkit.js:35:106)
    at Object.internals.handler (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\node_modules\hapi\lib\handler.js:52:48)
    at exports.execute (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\node_modules\hapi\lib\handler.js:37:36)
    at module.exports.internals.Request._lifecycle (C:\Users\ME\Downloads\samsung-remote-models-2014-and-newer-master\samsung-remote-models-2014-and-newer-master\example\node_modules\hapi\lib\request.js:261:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I haven't seen anything similar to this (then again I have the attention span and memory of a gnat so could have missed it) so I'm not sure if this means the TV is unable to be connected to or that I'm doing something wrong.

I used Yarn to install after accidentally installing with npm (I deleted everything npm added I believe) and was using Yarn to run this like in your README. I'm on a Win10Home64bit machine v1803.

If you could point me in the right direction it would be much appreciated :D
If there's anything else you'd like to know, don't hesitate to ask!

**Comment by tproenca** [comment]
I'm having the same problem with my Samsung The Frame TV
