### ISSUE TITLE
Confirmed: working on UE55HU7500

### ISSUE THREAD

**Issue by riemers** [tdudek/samsung-remote-models-2014-and-newer#3]
At first i got this error message.

```
Fetching device info
Debug: internal, implementation, error
    TypeError: Cannot read property 'requestPin' of null
    at SamsungTv.requestPin (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\node_modules\samsung-remote\lib\SamsungTv.js:47:25)
    at handler (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\server.js:46:22)
    at module.exports.internals.Manager.execute (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\node_modules\hapi\lib\toolkit.js:35:106)
    at Object.internals.handler (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\node_modules\hapi\lib\handler.js:52:48)
    at exports.execute (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\node_modules\hapi\lib\handler.js:37:36)
    at module.exports.internals.Request._lifecycle (C:\Users\rieme\WebstormProjects\samsung-remote-models-2014-and-newer\example\node_modules\hapi\lib\request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

On second try it did see my device.

Output for reference:

```
Initializing device configuration
Fetching device info
Received device info
Device info:  { id: '05f5e101-0064-1000-bc6f-5056bf7d0524',
  name: '[TV]Samsung LED55' }
Initialization successful { id: '05f5e101-0064-1000-bc6f-5056bf7d0524',
  name: '[TV]Samsung LED55' }
Step 0: Start pairing
Step 0, responseStatus 200
PIN showing at TV
Confirming pin 4147
Step 1: Saying hello to the server
Generated serverHello 010200000000000000008A00000006363534333231945D6127908D259492FA63517D69B4048DA77A9917AEF946A29C6F1BF8A9EEF0FD49CA15FBB07688A56A004F0B94C30D1954BBC3E332D3E359145F1C3E2B063099E28E5A5378C31BE66E724A1A664D4AA23263B3D84C9
46B721BAD84C976286D907A37A64266356CDDF0F6AA1621A24582FF64AB972F45C751DB4B7351D096D10000000000
hello auth data { auth_type: 'SPC',
  request_id: '0',
  GeneratorClientHello: '010100000000000000009E00000006363534333231483A750F5A5315DA6B088A7999F23483AC0D8ED00D9962BA3900A03450FA2ED582CFCD24658875691487DFE2C868A9387DB470F07A20D5BA0E6D5BD3862AFBAB74B9BF21870468A4B1F5279AA7F72F7920BAF9AFBB
A6958D81C5420B5C65EF38E9A187A48EBD7F883780DB22697A8EFA37B6D0D96DECA43C91266B30669F9E68553BD4EDFE04A63CDF0D6C57BB949D8E8F93B2B50000000000' }
hello verified
Step 2: Acknowledging
generatedServerAcknowledge: 01030000000000000000144118C3A4752785A2304AAD6DD8137D5EC6F950460000000000
ack auth data { auth_type: 'SPC',
  request_id: '0',
  ClientAckMsg: '0104000000000000000014FF0A745A136E7218A392618C1E89EB4C568F62650000000000',
  session_id: '1' }
client ack true
identity { sessionId: '1', aesKey: '4bd03922ef8d6b111cbf971df5725e22' }
PIN confirmation succeeded. Identity:  { sessionId: '1', aesKey: '4bd03922ef8d6b111cbf971df5725e22' }
Handshake: guz8hxY-IZuahVGPAQNJ
Opening new websocket
Connection established
SOCKET MESSAGE:  1::/com.samsung.companion
buildEmitMessage: registerPush, payload: {"body":"[219,206,247,135,54,47,242,157,254,134,110,166,166,7,119,187,90,145,30,54,7,86,157,219,217,122,183,57,72,32,14,137,213,72,114,48,152,141,252,189,249,176,55,143,167,196,200,119]","Session_
Id":1}
buildEmitMessage: registerPush, payload: {"body":"[219,206,247,135,54,47,242,157,254,134,110,166,166,7,119,187,125,183,49,245,221,234,104,89,255,233,59,5,178,183,121,239,43,57,108,232,37,181,1,86,76,53,225,250,28,22,18,174]","Session_Id"
:1}
buildEmitMessage: callCommon, payload: {"body":"[252,214,194,129,177,125,230,250,235,91,162,56,190,70,73,14,198,118,153,16,203,137,149,233,217,0,197,185,169,79,15,204,74,107,255,162,224,220,123,100,194,134,78,79,163,181,174,129,21,72,99,
63,153,1,187,11,184,143,46,220,78,40,147,63,197,199,199,227,133,100,150,118,222,12,157,2,207,139,248,218]","Session_Id":1}
unknown message received: 1::/com.samsung.companion
SOCKET MESSAGE:  5::/com.samsung.companion:
Handle Event: receiveCommon
receiveCommon: [126,246,50,94,155,170,64,150,255,207,224,213,55,97,126,42,51,48,151,29,204,129,248,236,212,134,101,130,167,255,14,49,144,248,43,39,104,16,249,219,54,171,180,205,39,186,22,166,38,134,41,245,51,108,221,100,235,225,188,207,2
34,219,237,203]
decrypted:  { plugin: 'NNavi', api: 'GetDUID', result: '2DCHVWLLD75OW' }
GetDUID: 2DCHVWLLD75OW: GetDUID
buildEmitMessage: callCommon, payload: {"body":"[252,214,194,129,177,125,230,250,235,91,162,56,190,70,73,14,198,118,153,16,203,137,149,233,217,0,197,185,169,79,15,204,136,10,204,64,51,187,211,201,252,61,45,15,250,213,87,93,196,254,94,246
,76,139,26,141,22,47,206,105,144,229,61,148,5,98,4,34,115,171,42,163,74,11,131,75,124,170,215,72,51,119,234,235,78,235,112,61,252,191,165,80,96,137,55,190,6,244,161,194,165,136,32,182,61,4,78,176,164,241,104,79,183,170,142,102,209,15,135
,218,156,27,60,47,181,136,182,77,197,233,132,152,135,248,221,236,11,50,230,32,8,180,79,150,169,31,55,140,53,138,178,22,52,86,44,234,196,211,12,89,165,89,147,140,54,120,215,69,131,158,250,229,122,38,87,99]","Session_Id":1}
SOCKET MESSAGE:  5::/com.samsung.companion:
Handle Event: receiveCommon
receiveCommon: [114,28,26,18,12,222,3,61,158,29,52,183,142,155,77,136,254,129,208,178,170,113,42,236,122,188,108,31,164,119,135,217,146,124,89,171,186,97,158,12,53,190,151,240,251,226,196,208,214,115,222,209,87,111,105,127,126,185,120,19
6,75,107,216,53]
decrypted:  { plugin: 'RemoteControl', api: 'SendRemoteKey', result: '1' }
SOCKET MESSAGE:  5::/com.samsung.companion:
Handle Event: receivePush
SOCKET MESSAGE:  5::/com.samsung.companion:
Handle Event: receivePush
```

**Comment by axel3rd** [comment]
Issue could be closed in IMO (`UE55HU7500` in working list, updated by #15).

**Comment by mwp007** [comment]
@riemers How did you fix this error ? 
I am porting to iobroker and have the same problem.

**Comment by riemers** [comment]
I think i had to do some pin stuff on my device.. but since its been like 3 years ago, i cannot recall 100% 😊
