### ISSUE TITLE
Need help to install on Synology DM

### ISSUE THREAD

**Issue by yasserabdalla** [tdudek/samsung-remote-models-2014-and-newer#36]
Hello Thomas,

Sounds a great plugin, I am a basic user with limited/no technical skills and I appreciate some guidance to install your tool on my Synology DM?

I run Homebridge on the Synology DM as well. I want to use it to control Samsung TV model # UN55JS8500. It will be great if I could use your tool from within HomeKit/Home app on my iPhone as well?

Thank you,

Yasser

**Comment by yasserabdalla** [comment]
I ran yarn install successfully but when I run the yarn start command, I get the error message below:

/homebridge # yarn start
yarn run v1.21.1
$ node server.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'hapi'
Require stack:
- /homebridge/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/server.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/homebridge/server.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/homebridge #

**Comment by yasserabdalla** [comment]
So my Synology uses Docker and Containers to run the Homebridge .. it will be great if I get some guidance to install your code in a container?

Thanks a lot
