### ISSUE TITLE
Not quite working with UE49KS7000 (2016)

### ISSUE THREAD

**Issue by twistedpixel** [tdudek/samsung-remote-models-2014-and-newer#8]
Didn't quite work on this model.

Started up the server, entered IP, found device.
PIN requested and showed unique PIN on tv but when I entered it in the interface, the 'waiting' animation started but never completed. The logs show that the PIN was accepted but seems it could not create the web socket connection.

Log is as follows:

> Initializing device configuration
Fetching device info
Received device info
Device info:  { id: '[REDACTED]',
  name: '[TV] Samsung 7 Series' }
Initialization successful { id: '[REDACTED]',
  name: '[TV] Samsung 7 Series' }
Step 0: Start pairing
Step 0, responseStatus 200
PIN showing at TV
Confirming pin 5367
Step 1: Saying hello to the server
Generated serverHello [REDACTED]
hello auth data { auth_type: 'SPC',
  request_id: '0',
  GeneratorClientHello: '[REDACTED]' }
hello verified
Step 2: Acknowledging
generatedServerAcknowledge: [REDACTED]
ack auth data { auth_type: 'SPC',
  request_id: '0',
  ClientAckMsg: '[REDACTED]',
  session_id: '3' }
client ack true
identity { sessionId: '3', aesKey: '[REDACTED]' }
PIN confirmation succeeded. Identity:  { sessionId: '3', aesKey: '[REDACTED]' }
Error while creating socket { FetchError: request to http://192.168.1.185:8000/socket.io/1 failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/node-fetch/lib/index.js:1376:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'request to http://192.168.1.185:8000/socket.io/1 failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Connection established

**Comment by twistedpixel** [comment]
Strangely, I got a different error the next time I tried:

> Initializing device configuration
Fetching device info
Received device info
Device info:  { id: '[REDACTED]',
  name: '[TV] Samsung 7 Series' }
Initialization successful { id: '[REDACTED]',
  name: '[TV] Samsung 7 Series' }
Step 0: Start pairing
Step 0, responseStatus 200
PIN showing at TV
Confirming pin 7546
Step 1: Saying hello to the server
Generated serverHello [REDACTED]
hello auth data { auth_type: 'SPC',
  request_id: '0',
  GeneratorClientHello: '[REDACTED]' }
hello verified
Step 2: Acknowledging
generatedServerAcknowledge: [REDACTED]
ack auth data { auth_type: 'SPC',
  request_id: '0',
  ClientAckMsg: '[REDACTED]',
  session_id: '1' }
client ack true
identity { sessionId: '1', aesKey: '[REDACTED]' }
PIN confirmation succeeded. Identity:  { sessionId: '1', aesKey: '[REDACTED]' }
Handshake: [REDACTED]
Opening new websocket
Connection established
SOCKET MESSAGE:  1::/com.samsung.companion
buildEmitMessage: registerPush, payload: {"body":"[144,128,226,146,222,224,139,176,24,42,41,41,247,41,74,242,52,190,124,7,177,65,219,87,236,155,152,197,57,59,216,6,184,86,131,122,145,93,249,94,72,91,64,184,99,70,49,21]","Session_Id":1}
buildEmitMessage: registerPush, payload: {"body":"[144,128,226,146,222,224,139,176,24,42,41,41,247,41,74,242,2,4,161,135,153,46,48,79,244,222,217,10,122,35,131,9,94,185,134,108,54,92,248,102,136,176,164,23,50,22,148,185]","Session_Id":1}
buildEmitMessage: callCommon, payload: {"body":"[245,54,54,18,106,71,78,255,68,179,249,65,174,142,124,60,104,191,212,184,176,187,97,0,200,175,143,141,233,198,70,103,201,146,31,96,124,53,240,180,41,101,118,51,56,1,116,219,26,86,37,202,72,53,120,74,115,204,45,46,151,224,44,173,41,207,76,220,53,42,150,51,120,189,186,242,207,194,41,14]","Session_Id":1}
unknown message received: 1::/com.samsung.companion
SOCKET MESSAGE:  5::/com.samsung.companion:
Handle Event: receiveCommon
receiveCommon: {"type":"Buffer","data":[138,236,222,172,138,17,113,65,75,30,153,51,130,19,35,241,175,31,16,185,28,105,209,7,96,36,49,144,63,29,186,167,18,149,190,209,125,182,159,1,49,53,79,171,153,239,248,77,38,185,38,14,169,7,17,251,210,154,81,6,123,224,39,54]}
handleEvent : unable to decrypt data RangeError: Invalid typed array length: -16
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8Array (native)
    at z.x (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Pairing/Encryption/asmcrypto.js:3:4608)
    at z.y [as decrypt] (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Pairing/Encryption/asmcrypto.js:3:4846)
    at Function.G [as decrypt] (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Pairing/Encryption/asmcrypto.js:3:6018)
    at Object.decryptData (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Pairing/Encryption/index.js:666:41)
    at messages.on.message (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Connection/SamsungTvConnection.js:74:45)
    at resolve (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Connection/Messages.js:28:31)
    at new Promise (<anonymous>)
    at Messages.handle (/Users/admin/Repos/samsung-remote-models-2014-and-newer/example/node_modules/samsung-remote/lib/Connection/Messages.js:27:12)
(node:13000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unable to handleEvent
(node:13000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by twistedpixel** [comment]
Actually, trying again I see that the error from my second comment happens first, then if I try again during the same session, I get the error in my first comment. I must have missed that the errors were different the first couple times I tried.

**Comment by jonadem** [comment]
I have the same issue on a UE55KU6650
